language: php
php:
  - 7.0
before_script:
  - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
script:
  - phpunit --configuration ./test/unit/php/phpunit.xml